version: 2
registries:
  npm-registry-registry-npmjs-org:
    type: npm-registry
    url: https://registry.npmjs.org
    token: "${{secrets.NPM_REGISTRY_REGISTRY_NPMJS_ORG_TOKEN}}"

updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: puppeteer
    versions:
    - 7.0.1
    - 7.1.0
    - 8.0.0
    - 9.0.0
  - dependency-name: core-js-pure
    versions:
    - 3.10.1
    - 3.11.0
    - 3.9.0
    - 3.9.1
  - dependency-name: rollup
    versions:
    - 2.38.3
    - 2.40.0
    - 2.41.2
    - 2.42.2
    - 2.45.0
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/core"
    versions:
    - 7.13.10
    - 7.13.13
    - 7.13.8
  - dependency-name: cypress
    versions:
    - 6.6.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.10
    - 7.13.8
    - 7.13.9
  - dependency-name: "@ideal-postcodes/postcode-lookup"
    versions:
    - 1.6.2
    - 1.7.0
  - dependency-name: semantic-release
    versions:
    - 17.4.0
    - 17.4.1
  - dependency-name: typescript
    versions:
    - 4.2.2
  registries:
  - npm-registry-registry-npmjs-org
